# Generated by Django 3.0.6 on 2020-05-27 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='activity_periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='webapp.User')),
            ],
        ),
    ]
